on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
        branches:
            - '*'

jobs:
    qa:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Run tests
              run: composer test

            - name: Check PHPCS
              run: composer check-code-style

            - name: Check PHPStan
              run: composer check-phpstan
